export const pieces = [
  "Ci vediamo fra... (gesticola)",
  "Un nonnulla",
  "Una dose generosa",
  "In fila come i soldatini",
  "Sono scelte private",
  "La mia tata tirolese",
  "Facciamo un test",
  "Che non si dica che non impiatto",
  "Io ci dormo fra due guanciali",
  "Molto molto bene",
  "Laido e corrotto",
  "Uno due e tre",
  "Molto carinamente",
  "Una smucinata propiziatoria",
  "LLLÀ!",
  "Ecco!",
  "POOI!",
  "Non serve ma ci sta bene",
  "Se non vi piace non ce lo mettete",
  "Molto molto YEAH",
  "Chi sono, Giotto?",
  "Grasso su grasso",
  "Er sellero",
  "(ansima)",
  "Al limite del micidiale",
  "Spolverata di pecorazzo",
];
