export const pieces = [
  "(ansima)",
  "(gesticola)",
  "ALÉ!",
  "Abbassiamo",
  "Accendiamo",
  "Aggeggio",
  "Al limite del micidiale",
  "Allora!",
  "Alziamo",
  "Becca d'aglio",
  "Burro",
  "Carinamente",
  "Ce ne mettete di meno",
  "Che non si dica che non impiatto",
  "Che spettacolo!",
  "Chi sono, Giotto?",
  "Ci prendiamo...",
  "Ci siamo EH",
  "Ci vediamo fra...",
  "Come se grandinasse",
  "Come se piovesse",
  "Direi che ci siamo",
  "Ecco!",
  "Er sellero",
  "Facciamo un test",
  "Grasso su grasso",
  "Guanciale",
  "In fila come i soldatini",
  "In questa maniera",
  "Io ci dormo fra due guanciali",
  "LLLÀ!",
  "La mia tata tirolese",
  "Laido e corrotto",
  "Lardo",
  "Loschissimo intruglio",
  "MMH!",
  "Molto molto YEAH",
  "Molto molto bene",
  "Molto molto buono",
  "Noce di cocco",
  "Non ce ne importa niente",
  "Non serve ma ci sta bene",
  "Olio",
  "POOI!",
  "Parmigiano reggiano 30 mesi",
  "Pecorazzo",
  "Sale SCRUPOLOSAMENTE grosso",
  "Salvia",
  "Se non vi piace non ce lo mettete",
  "Sfracagnare",
  "Smucinata",
  "Sono scelte private",
  "Spegniamo",
  "Spolverata",
  "Strepitosa",
  "Suadentemente",
  "Un nonnulla",
  "Una dose generosa",
  "Uno due e tre",
];
